using Domain.Entidades;
using Domain.Interfaces.Repositorio;

namespace Banco.Repositorio
{  
    public class EpcRepositorio : IEpcRepositorio
    {
        public List<LeituraEpc> ListaEpcs()
        {
            var baseTime = DateTime.Now;
            return
            [
                 new() { Hex = "000002001", DataRegistro = baseTime.AddSeconds(-90),
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002002", DataRegistro = baseTime.AddSeconds(-85),
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002003", DataRegistro = baseTime.AddSeconds(-80),
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002004", DataRegistro = baseTime.AddSeconds(-75),
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002001", DataRegistro = baseTime.AddSeconds(-70),
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002101", DataRegistro = baseTime.AddSeconds(-60),
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002102", DataRegistro = baseTime.AddSeconds(-45),
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002103", DataRegistro = baseTime.AddSeconds(-40),
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002200", DataRegistro = baseTime.AddSeconds(-55),
                    CodigoVariacao = 1, NomeProduto = "Fanta Laranja" },
                new() { Hex = "000002201", DataRegistro = baseTime.AddSeconds(-65),
                    CodigoVariacao = 1, NomeProduto = "Fanta Laranja" },
                new() { Hex = "000002300", DataRegistro = baseTime.AddSeconds(-60),
                    CodigoVariacao = 2, NomeProduto = "Fanta Uva" },
                new() { Hex = "000002301", DataRegistro = baseTime.AddSeconds(-65),
                    CodigoVariacao = 2, NomeProduto = "Fanta Uva" },
                new() { Hex = "000002001", DataRegistro = baseTime.AddSeconds(-60),
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002002", DataRegistro = baseTime.AddSeconds(-55),
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002003", DataRegistro = baseTime.AddSeconds(-45),
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002004", DataRegistro = baseTime.AddSeconds(-50),
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002001", DataRegistro = baseTime.AddSeconds(-40),
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002101", DataRegistro = baseTime.AddSeconds(-35),
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002102", DataRegistro = baseTime.AddSeconds(-30),
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002103", DataRegistro = baseTime.AddSeconds(-24),
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002200", DataRegistro = baseTime.AddSeconds(-30),
                    CodigoVariacao = 1, NomeProduto = "Fanta Laranja" },
                new() { Hex = "000002201", DataRegistro = baseTime.AddSeconds(-20),
                    CodigoVariacao = 1, NomeProduto = "Fanta Laranja" },
                new() { Hex = "000002300", DataRegistro = baseTime.AddSeconds(-15),
                    CodigoVariacao = 2, NomeProduto = "Fanta Uva" },
                new() { Hex = "000002301", DataRegistro = baseTime.AddSeconds(-15),
                    CodigoVariacao = 2, NomeProduto = "Fanta Uva" },
                new() { Hex = "000002001", DataRegistro = baseTime.AddSeconds(-10), 
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002002", DataRegistro = baseTime.AddSeconds(-11), 
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002003", DataRegistro = baseTime.AddSeconds(-12), 
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002004", DataRegistro = baseTime.AddSeconds(-3), 
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002001", DataRegistro = baseTime.AddSeconds(-10), 
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002101", DataRegistro = baseTime.AddSeconds(-2), 
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002102", DataRegistro = baseTime.AddSeconds(-2), 
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002103", DataRegistro = baseTime.AddSeconds(-8), 
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002200", DataRegistro = baseTime.AddSeconds(-7), 
                    CodigoVariacao = 1, NomeProduto = "Fanta Laranja" },
                new() { Hex = "000002201", DataRegistro = baseTime.AddSeconds(-5), 
                    CodigoVariacao = 1, NomeProduto = "Fanta Laranja" },
                new() { Hex = "000002300", DataRegistro = baseTime.AddSeconds(-3), 
                    CodigoVariacao = 2, NomeProduto = "Fanta Uva" },
                new() { Hex = "000002301", DataRegistro = baseTime.AddSeconds(-7), 
                    CodigoVariacao = 2, NomeProduto = "Fanta Uva" },
                new() { Hex = "000002001", DataRegistro = baseTime.AddSeconds(-8), 
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002002", DataRegistro = baseTime.AddSeconds(-11), 
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002003", DataRegistro = baseTime.AddSeconds(-10), 
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002004", DataRegistro = baseTime.AddSeconds(-9), 
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002001", DataRegistro = baseTime.AddSeconds(-8), 
                    CodigoVariacao = 1, NomeProduto = "Coca Zero" },
                new() { Hex = "000002101", DataRegistro = baseTime.AddSeconds(-7),
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002102", DataRegistro = baseTime.AddSeconds(-5), 
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002103", DataRegistro = baseTime.AddSeconds(-5), 
                    CodigoVariacao = 2, NomeProduto = "Coca Normal" },
                new() { Hex = "000002200", DataRegistro = baseTime.AddSeconds(-2),
                    CodigoVariacao = 1, NomeProduto = "Fanta Laranja" },
                new() { Hex = "000002201", DataRegistro = baseTime.AddSeconds(-1), 
                    CodigoVariacao = 1, NomeProduto = "Fanta Laranja" },
                new() { Hex = "000002300", DataRegistro = baseTime, 
                    CodigoVariacao = 2, NomeProduto = "Fanta Uva" },
                new() { Hex = "000002301", DataRegistro = baseTime,
                    CodigoVariacao = 2, NomeProduto = "Fanta Uva" }
            ];
        }
    }
}
